uber-web/jazelle

- commands/node.js
- index.js
`jz node -p 'process.versions.pnp'` should not log `undefined`
> Fix jz node handling of deps under yarn 2

- commands/add.js
- package.json
- rules/execute-command.js
- rules/web-monorepo.bzl
- tests/fixtures/script/a/package.json
- tests/index.js
- utils/generate-bazel-build-rules.js
This PR adds several optimizations to the bazel build process.
1. Update BUILD.bazel file generation to use library target whenever possible
The web_binary build target is significantly more expensive than the web_library target. Defaulting to the web_library target whenever possible significantly reduces bazel overhead.
2. Remove support for pre/post build package.json scripts
Yarn2 has also removed support for pre/post build package.json scripts as they can lead to confusing behavior. Removing this allows us to further reduce overhead in the web_binary target. (See https://yarnpkg.com/advanced/lifecycle-scripts/)
3. Add support for ${NODE} and ${ROOT_DIR} interpolations in web_binary build commands
In large monorepos, each call to yarn incurs overhead. Rather than trying to call yarn to …
> Optimize bazel integration

- rules/untar.js
- tests/fixtures/bazel-dependent-builds/a/package.json
- tests/fixtures/bazel-dependent-builds/b/package.json
- tests/fixtures/bazel-dependent-builds/c/package.json
During build phase, we must untar build outputs into sandbox build dir in addition to the bazel-out dir if we want to have the ability for a build target to depend on the output of another target.
> Untar build outputs into sandbox build dir

- bin/cli.sh
The pre/post command logic tries to read manifest.json, but that file isn't necessarily there if you run jazelle commands outside a monorepo (e.g. jz init, or jz version)
> Don't throw errors when running jz outside of a monorepo

- package.json
- prevent yarn from clobbering `vendor/.gitignore`
- add `--flat` and `--frozen-lockfile`
> Fix update-vendor script

- README.md
- commands/scaffold.js
- tests/index.js
Fix for this [issue](https://t3.uberinternal.com/browse/WPT-7116?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D)
Also fixed some outdated docs
> [bugfix] ensure scaffold adds project to package.json not manifest.json

- rules/execute-command.js
If gen_src applies repo-wide, then the logic to delete extraneous files will pick up anything within folders that happen to have a matching name, e.g.
```
- root
- my-project
- BUILD.bazel
- gen_src = ["artifacts"]
- artifacts
- foo.txt <- should be regenerated
- artifacts
- bar.txt <- should NOT be deleted 
```
> Ensure gen_src only applies within the project's folder rather than repo-wide

- commands/outdated.js
- tests/fixtures/outdated/a/package.json
Refactors the logic from Brady Thornton's [D5420795](https://code.uberinternal.com/D5420795) (internal) into the `jz outdated` command.
In particular, it adds batching of multiple packages into a single `npm info` call and runs all of these requests in parallel.
---
Before:
```
jz outdated  2377.82s user 253.81s system 54% cpu 1:21:02.60 total
```
After:
```
jz outdated  597.43s user 66.25s system 720% cpu 1:32.11 total
```
Roughly a 2-order of magnitude improvement in performance.
> Performance improvements for `jz outdated` command

- commands/outdated.js
- index.js
- tests/fixtures/outdated/b/package.json
- tests/fixtures/outdated/manifest.json
- tests/index.js
Similar to the output from [D5420795](https://code.uberinternal.com/D5420795), with the exception of the `latestIsGreater` field.
Example output:
```
{"packageName":"@babel/plugin-transform-flow-strip-types","installed":["7.10.4"],"latest":"7.12.13"}
{"packageName":"@babel/preset-env","installed":["7.12.1"],"latest":"7.12.16"}
{"packageName":"@babel/preset-react","installed":["7.12.1"],"latest":"7.12.13"}
{"packageName":"graphql-parse-resolve-info","installed":["4.7.0"],"latest":"4.11.0"}
{"packageName":"@turf/helpers","installed":["4.7.3"],"latest":"6.3.0"}
{"packageName":"eslint-import-resolver-node","installed":["0.3.3"],"latest":"0.3.4"}
{"packageName":"nodemon","installed":["2.0.4"],"latest":"2.0.7"}
{"packageName":"fusion-plugin-react-redux","installed":["2.1.3"],"latest":"2.2.3"} …
```
> Add --json option to `jazelle outdated` command

- commands/purge.js
It currently doesn't clean `.yarn` dir
> Fix purge command

- utils/find-changed-targets.js
Rather than querying every single file, query only one file per folder, since that's sufficient to tell which target the file group belongs to, given how jazelle generates build files.
This should also make the command run faster
> Don't crash when `jazelle changes` receives a large file list

- commands/bump.js
- commands/sort.js
- commands/upgrade.js
- index.js
Add `jz sort` command
Also, don't sort package.jsons on bump or upgrade command
This is to avoid massive diffs due to package.json fields getting sorted in irrelevant packages
> Do not sort package.json files on bump or upgrade commands

- README.md
- commands/outdated.js
- index.js
Adds a `--limit` option to the `jz outdated` command.  On older machines, the `jz outdated` command can slow things to a crawl so this will throttle the number of `npm info` requests being made simultaneously.
Here are some benchmarks:
```
jz outdated --json --dedup 368.75s user 40.41s system 299% cpu 2:16.40 total
jz outdated --json --dedup --limit 10 321.11s user 33.82s system 55% cpu 10:36.87 total
jz outdated --json --dedup --limit 50 363.30s user 39.50s system 205% cpu 3:15.83 total
jz outdated --json --dedup --limit 100 370.76s user 40.99s system 294% cpu 2:19.70 total
jz outdated --json --dedup --limit 10000 419.34s user 46.53s system 559% cpu 1:23.33 total
```
> Adds --limit option for performance reasons to outdated command

- commands/upgrade.js
After running `jz upgrade ...` or `jz bump ...`, the PnP map gets stale and a `jz install` is required. This PR makes it so that the subsequent `jz install` call is not needed.
> Restore pnp map after upgrade and bump

- commands/build.js
- utils/get-manifest.js
Add support for `hasSandboxIO` config property in manifest.json, which makes `jz build` not error if the underlying command is known to cause IO writes in build sandbox
> Add support for hasSandboxIO config property in manifest.json

- commands/test.js
Turns out the pass through args are working correctly. The real issue has to do with jest dealing with watching symlinks. Until jest can handle that correctly, we can just throw an error and suggest using jazelle yarn test --watch
> Throw error when --watch flag is passed to test command

- tests/fixtures/bazel-command-retries/BUILD.bazel
- tests/fixtures/bazel-command-retries/WORKSPACE
- tests/fixtures/bazel-command-retries/manifest.json
- tests/fixtures/bazel-command-retries/package.json
- tests/fixtures/bazel-command-retries/projects/a/package.json
- tests/fixtures/bazel-command-retries/projects/b/package.json
- tests/fixtures/bazel-command-retries/third_party/jazelle/scripts/build-file-template.js
- tests/index.js
- utils/bazel-commands.js
This adds support for automatically retrying bazel commands when receiving a BulkTransferException. By default it will retry up to 5 times with an exponential backoff starting at 1000ms. Tests included
> Add support for retrying bazel commands on BulkTransferException

- README.md
- rules/execute-command.js
- rules/jazelle.bzl
Allow yarn.lock and .pnp.cjs to be omitted from BUILD.bazel files
This allows us to not trigger global cache busts when yarn.lock changes
> Allow omission of yarn.lock and .pnp.cjs from BUILD.bazel files

- README.md
- rules/execute-command.js
- rules/web-monorepo.bzl
Adds an additional option to bypass the auto loading of the pnp.js file when commands are being run with jazelle. Reason being some scripts can be optimized to use only NodeJS libraries and not require any node_modules to run and this vastly improves script start up performance if the pnp.js file is large.
The flag is set to opt in so scripts need to explicitly define `skip_pnp` and set it to `True` in order to activate this.
> Add skip_pnp option to web-monorepo rule

- README.md
- commands/install.js
- utils/execute-hook.js
This allows for conditionally skipping the install when running `jz install` or `jz ci`. Useful for intercepting install process to pull a dependency cache instead
> Add `bool_shouldinstall` hook

- rules/execute-command.js
Currently, if a user terminal is in a project folder and they run a command that is meant to be run from the root folder, an error occurs (or worse, if a global executable of the same name exists, that runs instead).
This change makes is so that running a root script from a non-root folder falls back to running the expected command instead of causing surprising things to happen
> Run root script instead of erroring if a user tries to run the root script from a project folder

- utils/starlark.js
The old parsing would fail on code like this:
```
foo(
srcs = glob(["**/*"]), # <- parsing of a call would terminate here instead of at the last line
deps = [
"//a:b"
],
)
```
This PR fixes parsing to account for parenthesis nesting
> Fix starlark parsing to account for nested parentheses in function calls

- utils/execute-hook.js
`jz install` was running in a sub process and threw:
```
process.stdout.moveCursor is not a function
```
so it seems there are some cases where these utilities aren't available
> Fix clearPrevLine in executeHook

- .gitignore
- README.md
- bin/bazelisk
- bin/init.sh
- rules/jazelle-dependencies.bzl
- templates/scaffold/WORKSPACE
- tests/fixtures/batch-test-group/WORKSPACE
- tests/fixtures/bazel-dependent-builds/WORKSPACE
- tests/fixtures/bazel-dependent-failure/WORKSPACE
- tests/fixtures/bazel-rules/WORKSPACE
- tests/fixtures/bin/WORKSPACE
- tests/fixtures/commands/WORKSPACE
- tests/fixtures/find-changed-targets/bazel/WORKSPACE
- tests/fixtures/report-mismatched-top-level-deps/WORKSPACE
- tests/fixtures/scaffold/WORKSPACE
- tests/fixtures/script/WORKSPACE
- tests/index.js
Add support for arm64 binaries
Note: see "Configure Bazel rules" section in README.md for breaking changes to the jazelle_dependencies rule in WORKSPACE
TL;DR: in WORKSPACE file, you should change node_sha256 to:
```python
jazelle_dependencies(
node_version = "16.15.0",
node_sha256 = {
"darwin-x64": "a6bb12bbf979d32137598e49d56d61bcddf8a8596c3442b44a9b3ace58dd4de8",
"linux-x64": "ebdf4dc9d992d19631f0931cca2fc33c6d0d382543639bc6560d31d5060a8372",
"win-x64": "dbe04e92b264468f2e4911bc901ed5bfbec35e0b27b24f0d29eff4c25e428604",
"darwin-arm64": "ad8d8fc5330ef47788f509c2af398c8060bb59acbe914070d0df684cd2d8d39b",
"linux-arm64": "b4080b86562c5397f32da7a0723b95b1df523cab4c757688a184e3f733a7df56",
},
yarn_version = "1.19.1",
yarn_sha256 = "fdbc534294caef9cc0d7384fb579ec758da7fc033392ce54e0e8268e4db24 …
```
> Add support for arm64

- rules/jazelle-dependencies.bzl
Use .get instead of array syntax to avoid error if user is on old version of jazelle locally
> Make cpu detection backwards compatible

- README.md
- commands/bump.js
- tests/index.js
- utils/find-changed-targets.js
- utils/get-downstreams.js
- utils/yarn-commands.js
Ticket: https://t3.uberinternal.com/browse/WPT-8662
`jz bump` errors out when it tries to update local downstreams that depending on the package via `workspace:*`. This updates it to just ignore those packages and not touch them
> [jz bump] Ignore packages using `workspace:*`

- tests/index.js
- utils/find-changed-targets.js
Jira: https://t3.uberinternal.com/browse/WPT-9167
Currently, `jz changes` with `--format targets` only returns `*_test` rules. This updates it to also include any `web_*` rules (e.g. `web_library`, `web_binary`, `web_executable`)
> [changes] return all web_* rules for `targets` format

- utils/get-all-dependencies.js
Previously running jz focus or jz install would crash due to attempting to read files that aren't checked out in a git sparse checkout. This change allows installation to run successfully
> Add support for sparse checkout to jz focus

- bin/cli.sh
This hooks allows jazelle commands to be prefixed or wrapped.
Examples:
- always prefix an env var, 
```
// manifest.json
{
"hooks": {
"cmd_prefix": "echo 'FOO=1'"
}
}
```
- always time commands
```
// manifest.json
{
"hooks": {
"cmd_prefix": "time"
}
}
```
- always print command instead of running
```
// manifest.json
{
"hooks": {
"cmd_prefix": "echo 'echo'"
}
}
```
Since the script is a shell script, it's also possible to conditionally prefix, etc
> implement cmd_prefix hook

- commands/add.js
- Don't throw error if .find returns null
> Don't error if `add` is called on a non-workspace project

- bin/cli.sh
make prefix hook cwd correct even if a command is run from a non-root dir
> make prefix cwd correct in prefix hook even if a command is run from a non-root dir

- rules/execute-command.js
The logic to load the PnP ESM loader need to be reversed, as previously it would skip the loader if it's present on the filesystem
> Ensure PnP ESM loader is used when available

- rules/execute-command.js
- tests/fixtures/bazel-rules/projects/b/package.json
- tests/index.js
Handle special case of Yarn v2 global script when executing a bazelified script
> Scripts containing `:` (the colon character) are globals to your project and can be called regardless of your current workspace. See https://yarnpkg.com/getting-started/qa#how-to-share-scripts-between-workspaces
> Handle special case of yarn v2 global script with bazel

- templates/scaffold/WORKSPACE
Fix #102 by adding the missing `darwin-arm64` entry in `WORKSPACE` template.
> Add missing darwin-arm64 entry

- commands/outdated.js
- tests/fixtures/outdated/a/package.json
- tests/fixtures/outdated/b/package.json
- tests/index.js
Change json format of `outdated` command so there is an array of objects.  Previously, it would output an array of arrays of objects and it wasn't valid json. 
Also, added updated test case to validate json formatting problem is resolved.
> Fixing json formatting for outdated command

- package.json
Changes since version 80 vbump:
```
(71accbb) Fixing json formatting for outdated command (#123) (Mike Kaufman)
(a7b542f) Sort BUILD.bazel file deps on install (#124) (Leo Horie)
(59e2e11) update error message (#121) (Leo Horie)
(b2e5611) Add missing darwin-arm64 entry (#118) (Salvatore Gentile)
(6c06235) v0.0.0-standalone.80 (#120) (shYkiSto)
```
> Vbump to version 81

- commands/install.js
When we skip installs, it returns before the bazel build file sorting logic runs, which should still run even if the full install isn't running. This moves the `bool_shouldinstall` hook logic after the sorting logic
> Move bool_shouldinstall hook after bazel sorting logic

- rules/untar.js
- tests/index.js
Without the patch:
File order usually doesn't matter when you create archives, but Jazelle uses the `tar ztf ${file}` command here https://github.com/uber-web/jazelle/blob/main/rules/untar.js#L49 which returns files in the order they were added to the archive and assumes that parent folders are before child folders.
This can result in errors because it tries to create a child directory before the parent directory.
i.e.
```
src/__gen__/foo/
src/__gen__/
```
When the untar copyToSourceFolder command runs it will result in the error:
`Error: ENOENT: no such file or directory, mkdir '...../src/__gen__/foo`
With the patch:
Changing the mkdir to create recursive files means the tar can be in any order and it will still work.
> Sort paths before generating tar.gz files from execute-command

- commands/add.js
- commands/upgrade.js
Follow up to #132, makes these commands run even faster by avoiding built-in build steps
> Simplify add/upgrade

- README.md
- commands/typecheck.js
- index.js
- utils/bazel-commands.js
- utils/execute-project-command.js
- utils/yarn-commands.js
Adds a new `typecheck` command.  Allows a consumer to declare a new rule with this name that can be invoked with `jz typecheck`.
```
_web_executable(
name = "typecheck",
command = "typecheck",
preserve_symlinks = "",
deps = ["{}:library".format(package), "{}:generate-tsconfig-references".format(package)],
)
```
Without these changes, the equivalent command folks would run is:
```
jz bazel run "<PATH_TO_PROJECT>:typecheck"
```
Running `jz typecheck` without it explicitly defined in Jazelle as it is here would proxy to the Yarn script which would not include running the respective `:library` or `generate-tsconfig-references` targets from the example above.
> Adds a 'typecheck' command

- tests/fixtures/bump/not-a-real-dep/package.json
- tests/fixtures/bump/not-a-real-downstream/package.json
- tests/fixtures/bump/not-a-real-project/package.json
- tests/index.js
Currently test references a unnamespaced package. Changing to the @uber namespace to avoid dependency confusion attacks
> Fix supply chain vuln in test

- utils/binary-paths.js
Determine the right yarn binary to run from the `yarnrc` configuration file for Yarn Berry projects
> Avoid spawning of extra intermediate yarn process

- README.md
- rules/execute-command.js
Expand list of files that get automatically smuggled into bazel sandbox to include all yarn files that are located at the project root level. This should help avoid invalidating build targets unnecessarily, in favor of using other means for determining when a project-level config change affects a given build target. Users may still explicitly include them in the bazel dependency graph to opt-out from this optimization.
> Handle smuggling of top-level yarn monorepo files into bazel sandbox

- rules/web-monorepo.bzl
WebBinary is used like a wrapper for different actions, including code generation. Allow it to accept a custom action name to differentiate easier for profiling / monitoring.
> Add custom mnemonic to WebBinary rule

- utils/find-changed-targets.js
`jazelle changes` requires changed files to be source file targets but I think this is an unnecessary constraint. Consider some arbitrary file like `README.md` which conceivably has no impact on builds, but will be updated often. I chose to add the `--keep_going` flag to ignore errors like below, but maybe there is a better way check early and exclude this class of file?
`Skipping 'src/a/README.md': no such target '//src/a:README.md': target 'README.md' not declared in package 'src/a' defined by /.../src/a/BUILD.bazel; however, a source file of this name exists.  (Perhaps add 'exports_files(["README.md"])' to src/a/BUILD?)`
> add keep_going flag to changed-targets query

- tests/fixtures/find-changed-targets/bazel/changes.txt
- utils/find-changed-targets.js
- utils/node-helpers.js
Because of how the `exec` fn in `node-helpers.js` is constructed, if the cmd returns with a non-zero exit code the stdout will not be returned. This does not play nicely with the previous change I made https://github.com/uber-web/jazelle/pull/147 where we can 'keep going' if changed files are not inputs to any bezel targets. In the previous PR I neglected to add a regression test for the behavior, and now following up with a test and fix.
> handle non-zero exit code in jazelle changes bazel query

- utils/find-changed-targets.js
I'm working on a diff that includes a couple thought changed files and `jazelle changes` throws a `E2BIG` error. Assuming this will resolve the issue, but I'm not familiar with how to test this branch with my local repo
> Reduce bazel query batch size to avoid E2BIG errors in large changesets

- bin/cli.sh
Conventionally bazel writes all of its info / system messages to `stderr`, preserving the `stdout` for the script / build output itself. Today, jazelle will write bazel logs collected during bootstrap to stdout polluting the standard output that may lead to unexpected behavior in user scripts, e.g., resolving a node binary via `jz bin-path node` may contain some junk breaking command substitution in scripts like this:
```bash
#!/bin/bash
NODE_PATH=$(jz bin-path node)
TEST=$($NODE_PATH -p "123") # this may throw command not found, if `jz bin-path node` output is polluted with other log messages
```
> Make sure bazel info messages are logged to stderr

- package.json
This includes following changes:
* https://github.com/uber-web/jazelle/pull/155
> Bump version to 0.0.0-standalone.92

- package.json
- utils/bazel-commands.js
- utils/find-changed-targets.js
Optimize Bazel target change detection and query execution:
* Introduce a `bazelQuery` utility function to handle Bazel queries using a temporary file, avoiding issues with command argument length limitations
* Refactor `findChangedBazelTargets` to utilize the new `bazelQuery` function
* Reduce the number of required queries to handle deleted files by querying all file labels in a single query using `--keep_going` option. Also, include all related source files instead of a single file to ensure we capture all of the package upstreams
* Remove unnecessary batching logic and clean up code
> Optimize bazel target change detection and query execution

- package.json
- utils/find-changed-targets.js
Remove an optimization logic from the findChangedTargets function. This optimization was originally designed to reduce query size by considering only one JS/TS file per directory, based on the assumption that all source files in a directory would map to the same target. However, this assumption does not hold when working with more granular targets, necessitating the retention of all files to calculate changed targets more accurately.
By removing this optimization, we ensure correct file handling for all types of files and targets. The query size limitation is no longer a concern since we switched to using query files. Despite the removal, there is no significant speed regression observed in our monorepo containing hundreds of thousands of files. Essentially, we are trading speed for …
> Use all modified files when calculating changed targets

- package.json
- tests/fixtures/find-changed-targets/bazel/changes-missing-files-label-only.txt
- tests/fixtures/find-changed-targets/bazel/changes-missing-files.txt
- tests/fixtures/find-changed-targets/bazel/package.json
- tests/fixtures/find-changed-targets/bazel/test-missing-file-dep/package.json
- tests/fixtures/find-changed-targets/bazel/test-missing-file-label-only-dep/BUILD.bazel
- tests/fixtures/find-changed-targets/bazel/test-missing-file-label-only-dep/package.json
- tests/fixtures/find-changed-targets/bazel/test-missing-file-label-only/package.json
- tests/fixtures/find-changed-targets/bazel/test-missing-file/package.json
- tests/fixtures/find-changed-targets/bazel/yarn.lock
- tests/index.js
- utils/bazel-commands.js
- utils/find-changed-targets.js
- utils/node-helpers.js
This change addresses a scenario where removed files may still be referenced in build files. Previously, `jazelle changes` would return an empty set in such cases. The update involves reading the bazel query's stdout to utilize known labels in subsequent queries.
> Handle missing files referenced in build files

- package.json
- utils/bazel-commands.js
This causes noisy logs in CI and gives us little value
> Remove `--sandbox_debug` bazel arg

- bin/bootstrap.sh
- commands/bazel.js
- utils/bazel-commands.js
Remove default startup options from bazel invocations in favor of the user/project configuration specified in the `.bazelrc`. This avoids introducing changes that would cause the server to restart between bazel invocations, reducing the likelihood of cache invalidation. E.g.,
```
% echo "WORKSPACE" | jz changes
...
% jz noop
WARNING: Running Bazel server needs to be killed, because the startup options are different.
Starting local Bazel server and connecting to it...
```
Example .bazelrc:
```
startup --host_jvm_args="-Xmx15g"
```
> Remove bazel startup options in favor of .bazelrc
